In [1]:
## Restructured model with germany data

In [2]:
import pickle
with open('../datasets/data/polymod_germany.pkl', 'rb') as file:
    data = pickle.load(file)

In [3]:
data['contacts']

,id,age_part,sex_part,occ_part,edu_part,hh_size,class_size,work_contacts_nr,age_cnt,sex_cnt,y
0,846,10.0,F,5.0,2.0,4,26.0,NaN,43.0,M,3.0
1,846,10.0,F,5.0,2.0,4,26.0,NaN,70.0,F,2.0
2,846,10.0,F,5.0,2.0,4,26.0,NaN,68.0,M,2.0
3,846,10.0,F,5.0,2.0,4,26.0,NaN,11.0,F,1.0
4,846,10.0,F,5.0,2.0,4,26.0,NaN,13.0,F,2.0
...,...,...,...,...,...,...,...,...,...,...,...
10648,2185,70.0,M,2.0,8.0,2,NaN,NaN,57.0,M,1.0
10649,2185,70.0,M,2.0,8.0,2,NaN,NaN,57.0,M,1.0
10650,2185,70.0,M,2.0,8.0,2,NaN,NaN,61.0,M,1.0
10651,2185,70.0,M,2.0,8.0,2,NaN,NaN,32.0,M,1.0
10652,2185,70.0,M,2.0,8.0,2,NaN,NaN,61.0,F,1.0

In [4]:
data['participants']

,id,age_part,sex_part,occ_part,edu_part,hh_size,class_size,work_contacts_nr,z
0,846,10.0,F,5.0,2.0,4,26.0,0.0,26.0
1,847,8.0,M,5.0,8.0,4,22.0,0.0,22.0
2,848,7.0,F,5.0,2.0,7,14.0,0.0,14.0
3,849,12.0,F,5.0,2.0,3,17.0,0.0,17.0
4,850,1.0,F,6.0,8.0,4,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
1336,2182,54.0,F,1.0,8.0,2,0.0,150.0,150.0
1337,2183,NaN,F,5.0,8.0,4,31.0,0.0,31.0
1338,2184,55.0,F,3.0,1.0,1,0.0,0.0,0.0
1339,2185,70.0,M,2.0,8.0,2,0.0,0.0,0.0
1340,2186,NaN,NaN,6.0,NaN,3,0.0,10.0,10.0

In [5]:
data['population']

     age     sex       P
0      0    Male  336808
1      1    Male  338210
2      2    Male  343332
3      3    Male  351954
4      4    Male  344300
..   ...     ...     ...
197   96  Female   26132
198   97  Female   18625
199   98  Female   12575
200   99  Female    8143
201  100  Female   11766

[202 rows x 3 columns]